/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
import edu.cmu.sphinx.api.Configuration;
import edu.cmu.sphinx.api.LiveSpeechRecognizer;
import edu.cmu.sphinx.api.SpeechResult;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

public class demo extends javax.swing.JFrame {

    /**
     * Creates new form demo
     */
    public demo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lbl_app_display = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\utility\\gifs\\Webp.net-resizeimage.gif")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 10, 395, 396);

        lbl_app_display.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        lbl_app_display.setText("Tap the Speaker Button to start recording your Voice");
        getContentPane().add(lbl_app_display);
        lbl_app_display.setBounds(550, 50, 580, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        /*VoiceLauncher vl = new VoiceLauncher();
        try {
            String str=vl.func();
            lbl_app_display.setText(str);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame_utility.class.getName()).log(Level.SEVERE, null, ex);
        }*/
      //  public class VoiceLauncher {
   // public static void main(String[] args) throws IOException {
        //Configuration Object
        Configuration configuration = new Configuration();
 
        // Set path to the acoustic model.
        configuration.setAcousticModelPath("resource:/edu/cmu/sphinx/models/en-us/en-us");
        // Set path to the dictionary.
        configuration.setDictionaryPath("3043.dic");
        // Set path to the language model.
        configuration.setLanguageModelPath("3043.lm");
 
        //Recognizer object, Pass the Configuration object
        LiveSpeechRecognizer recognize = null;
        try {
            recognize = new LiveSpeechRecognizer(configuration);
        } catch (IOException ex) {
            Logger.getLogger(demo.class.getName()).log(Level.SEVERE, null, ex);
        }
        lbl_app_display.setText("start speaking");
        System.out.println("start speaking");
        //Start Recognition Process (The bool parameter clears the previous cache if true)
        recognize.startRecognition(true);
 
        //Creating SpeechResult object
        SpeechResult result;
 
        //Check if recognizer recognized the speech
        while ((result = recognize.getResult()) != null)
        {
 
            //Get the recognized speech
            String command = result.getHypothesis();
            String work = null;
            Process p;
            
           // String a=;
             //String a1 = ;
            
 
            if(command.equalsIgnoreCase("open file manager"))
            {
                System.out.println("open file manager");
                    work = "explorer" ;
                    lbl_app_display.setText("open file manager");
            }
            else if (command.equalsIgnoreCase("close file manager"))
            {
                System.out.println("close file manager");
            work = "Taskkill /IM explorer.exe /F";
            lbl_app_display.setText("close file manager");
             } 
            else if (command.equalsIgnoreCase("open browser"))
            {
                System.out.println("open browser!");
               work = "C:\\Users\\user\\AppData\\Local\\Google\\Chrome\\Application\\chrome.exe";
               lbl_app_display.setText("open browser");
             }
            else if (command.equalsIgnoreCase("close browser"))
            {
                System.out.println("close browser");
               work = "Taskkill /IM chrome.exe /F";
               lbl_app_display.setText("close browser");
               

            }
        
            //In case command recognized is none of the above hence work might be null
            if(work != null) {
                try {
                    //Execute the command
                    p = Runtime.getRuntime().exec(work);
                } catch (IOException ex) {
                    Logger.getLogger(demo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
  //  }
//}

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
           /* UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        java.awt.EventQueue.invokeLater(() -> {
            new demo().setVisible(true);
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbl_app_display;
    // End of variables declaration//GEN-END:variables

/*public void run() throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException
{
       UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        new app_frame().setVisible(true);
}*/


}